### ISSUE TITLE
Where do you get the numberof obstacles you need to optimize?

### ISSUE THREAD

**Issue by yodahuang** [leonidk/Box2D#1]
In `get_params_part_n` functions, the number of obstacles are hard-coded there. How does the program know the dimention for `x`?

**Comment by yodahuang** [comment]
The width and height are hard-coded also. How does the program know them when optimizing?

**Comment by alspitz** [comment]
The number of obstacles is hardcoded in each get_params function. The dimension of x is implictly defined by the number of elements in the bounds list for that part (the get_bounds_part_n functions). Some optimizers use the dimension of the provided bounds (e.g. differential evolution) and others need an initial guess (e.g. slsqp), which is created by randomly sampling a vector inside the bounds.

The width and height of each obstacle is also hard coded inside the get_params functions. Those are the two values after the width, height, and angle of an obstacle. E.g. For part 5, the configurable obstacles have a width of 4.0 and a height of 0.8. In principle, you can use values from x to define the widths and heights and optimize over them, but we have not done that.

**Comment by yodahuang** [comment]
Thanks! I understand the first question now. But how does the optimizer know the width is hard-coded to be 4.0 and 0.8? I don't see these numbers passed to optimizers. 

The problem I am solving is that I have some existing blocks with different width and height. I would like the optimizer to tell me what's the best `x`, `y` and `theta` for each of these unique blocks. Do you have any ideas on that?

Thanks

**Comment by alspitz** [comment]
The optimizer doesn't know the width and height. It doesn't know anything about blocks or a ball either. It only knows about the numbers it can set and the final cost. The width and height are used in the simulation to compute the ball trajectory, which is then used to compute the final cost.

**Comment by yodahuang** [comment]
Get it. In the HW2 description, it is said in part 4,

> The ball is dropped at (431, 181) in pixel coordinates. The obstacles are really 0.25m long and 0.037m high, so you also need to convert the pixel values to meters

I wonder where is the ball initial location configured, and is the pixel->meter thing implemented?

**Comment by alspitz** [comment]
The pixel to meter transformation is really only used in part 5 and is accomplished by scaling the provided pixel trajectory to the units of the simulated ball trajectory (see https://github.com/leonidk/Box2D/blob/master/optimize.py#L91). The aspect ratio of the obstacles is roughly matched using the hardcoded width and heights.

The initial ball position and velocity are not super relevant but can be set in Testbed/Tests/BulletTest.h (https://github.com/leonidk/Box2D/blob/master/Testbed/Tests/BulletTest.h#L126).

**Comment by yodahuang** [comment]
Now that I look hard into your implementation I feel like I can write my own optimizer now...
Here's two new questions:
- Will changing dimensions of the parameters, i.e. gravity, width/height of the blocks affect numerical stability? Should I scale it as you do with the rotation?
- Oh you actually have a `myFunc` to handle all the testBed stuff...

**Comment by leonidk** [comment]
1. I'm not sure what you mean. Depending on the solver, this may or may not affect solution quality. CMA-ES specifically takes an initial sigma and if your parameters are non-uniformly scaled, it may be bad.
2. this is to improve simulation time. It's 10 to 100x faster for these types of simulations to simply do it via a library instead of calling an executable.
